# Source - https://stackoverflow.com/q
# Posted by user1502133
# Retrieved 2025-12-07, License - CC BY-SA 4.0

version: '3.6'

services:
  keycloak_web:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak_web
    environment:
      
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakdb:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak # have to change this later after dev

      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin1"
      
      
      KC_HOSTNAME: "https://auth.eldonbaitandtackle.net"
      KC_HOSTNAME_ADMIN_URL: "http://100.73.81.46:8080"
      KC_PROXY_HEADERS: "xforwarded"

      KC_HTTP_ENABLED: "true"

      KC_HOSTNAME_STRICT: 'true'
      
      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: 'true'
      KC_HEALTH_ENABLED: 'true'
    command: start-dev
    networks:
      - keycloak_net
    depends_on:
      - keycloakdb
    ports:
      - '8080:8080'


  keycloakdb:
    image: postgres:16
    container_name: keycloakdb
    hostname: keycloakdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    networks:
      - keycloak_net
volumes:
  postgres_data:


networks:
  hsn_net:
    external: true
    driver: bridge
  keycloak_net:
    external: true
    driver: bridge